export const SCREEN_NAME = {
  STACK_HOME_SCREEN: 'STACK_HOME_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  PLACE_SCREEN: 'PLACE_SCREEN',
  SETTING_SCREEN: 'SETTING_SCREEN',
  DETAIL_SCREEN: 'DETAIL_SCREEN',
  BOTTOM_TAB_MAIN_SCREEN: 'BOTTOM_TAB_MAIN_SCREEN',
  TEST_SCREEN: 'TEST_SCREEN',
};
