import {StyleSheet, Text, View} from 'react-native';
import React from 'react';
import {COLORS} from '../../../../constants/colors';
import {scale, scaleHeight} from '../../../../utils/fontConfig';

const styles = StyleSheet.create({
  backgroundContainer1: {
    width: scale(375),
    height: scaleHeight(31),
    position: 'absolute',
    top: scaleHeight(31),
    left: 0,
    zIndex: 100,
    backgroundColor: COLORS.white,
  },
  item1: {
    backgroundColor: '#2669FF',
    width: scale(375),
    height: scaleHeight(31),
    position: 'absolute',
    top: 0,
    left: 0,
    zIndex: 10,
    borderBottomRightRadius: scale(25),
  },
  border1: {
    flex: 1,
    backgroundColor: 'rgba(38, 105, 255, 0.85)',
  },
  backgroundContainer2: {
    width: scale(50),
    height: scaleHeight(31),
    position: 'absolute',
    top: scaleHeight(62),
    right: 0,
    zIndex: 100,
    backgroundColor: COLORS.white,
  },
  item2: {
    backgroundColor: 'rgba(38, 105, 255, 0.70)',
    width: scale(50),
    height: scaleHeight(31),
    position: 'absolute',
    top: 0,
    right: 0,
    zIndex: 10,
    borderBottomRightRadius: scale(25),
  },
  border2: {
    flex: 1,
    backgroundColor: 'rgba(38, 105, 255, 0.50)',
  },
  backgroundContainer3: {
    width: scale(50),
    height: scaleHeight(31),
    position: 'absolute',
    top: scaleHeight(93),
    right: 0,
    zIndex: 100,
    backgroundColor: COLORS.white,
  },
  item3: {
    backgroundColor: 'rgba(38, 105, 255, 0.4)',
    width: scale(50),
    height: scaleHeight(31),
    position: 'absolute',
    top: 0,
    right: 0,
    zIndex: 10,
    borderBottomRightRadius: scale(25),
  },
  border3: {
    flex: 1,
    backgroundColor: 'rgba(38, 105, 255, 0.2)',
  },
  backgroundContainer4: {
    width: scale(50),
    height: scaleHeight(31),
    position: 'absolute',
    top: scaleHeight(124),
    right: 0,
    zIndex: 100,
    backgroundColor: COLORS.white,
  },
  item4: {
    backgroundColor: 'rgba(38, 105, 255, 0.2)',
    width: scale(50),
    height: scaleHeight(31),
    position: 'absolute',
    top: 0,
    right: 0,
    zIndex: 10,
    borderBottomRightRadius: scale(25),
  },
  border4: {
    flex: 1,
    backgroundColor: 'rgba(38, 105, 255, 0)',
  },
  roundContainer1: {
    position: 'absolute',
    left: 0,
  },
  roundItem1: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: scale(415),
    height: scaleHeight(321),
    backgroundColor: '#2669FF',
  },
  round1: {
    position: 'absolute',
    left: 0,
    top: scaleHeight(62),
    width: scale(200),
    height: scaleHeight(900),
    backgroundColor: COLORS.white,
    borderTopLeftRadius: scale(1000),
  },
  roundround1: {
    position: 'absolute',
    left: scale(200),
    top: scaleHeight(62),
    width: scale(200),
    height: scaleHeight(900),
    backgroundColor: COLORS.white,
  },
  roundContainer2: {
    top: scaleHeight(31),
    position: 'absolute',
    left: 0,
    zIndex: 1,
  },
  roundItem2: {
    position: 'absolute',
    borderTopLeftRadius: scale(40),
    left: 0,
    top: 0,
    width: scale(415),
    height: scaleHeight(321),
    backgroundColor: '#2669FF',
    opacity: 0.7,
  },
  round2: {
    position: 'absolute',
    left: 0,
    top: scaleHeight(62),
    width: scale(200),
    height: scaleHeight(900),
    backgroundColor: COLORS.white,
    borderTopLeftRadius: scale(1000),
  },
  roundround2: {
    position: 'absolute',
    left: scale(200),
    top: scaleHeight(62),
    width: scale(200),
    height: scaleHeight(900),
    backgroundColor: COLORS.white,
  },
  roundContainer3: {
    top: scaleHeight(62),
    position: 'absolute',
    left: 0,
    backgroundColor: 'red',
    zIndex: 2,
  },
  roundItem3: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: scale(415),
    height: scaleHeight(321),
    backgroundColor: '#2669FF',
    opacity: 0.4,
    borderTopLeftRadius: scale(180),
  },
  round3: {
    position: 'absolute',
    left: 0,
    top: scaleHeight(62),
    width: scale(200),
    height: scaleHeight(900),
    backgroundColor: COLORS.white,
    borderTopLeftRadius: scale(1000),
  },
  roundround3: {
    position: 'absolute',
    left: scale(200),
    top: scaleHeight(62),
    width: scale(200),
    height: scaleHeight(900),
    backgroundColor: COLORS.white,
  },
  roundContainer4: {
    top: scaleHeight(62),
    position: 'absolute',
    left: 0,
    backgroundColor: 'red',
    zIndex: 3,
  },
  roundItem4: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: scale(415),
    height: scaleHeight(321),
    backgroundColor: '#2669FF',
    opacity: 0.2,
    borderTopLeftRadius: scale(180),
  },
  round4: {
    position: 'absolute',
    left: 0,
    top: scaleHeight(93),
    width: scale(200),
    height: scaleHeight(900),
    backgroundColor: COLORS.white,
    borderTopLeftRadius: scale(1000),
  },
  roundround4: {
    position: 'absolute',
    left: scale(200),
    top: scaleHeight(93),
    width: scale(200),
    height: scaleHeight(900),
    backgroundColor: COLORS.white,
  },
});

export default styles;
